services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - apsp-network

  migration:
    build:
      context: .
      dockerfile: docker/Dockerfile.migration
    env_file:
      - .env
    container_name: migration
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - apsp-network

  main-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    container_name: main-app
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    restart: always
    networks: 
      - apsp-network

volumes:
  postgres-data:
    name: postgres-data
networks:
  apsp-network:
    driver: bridge